name: lovelust
description: Track and take care of your sexual health
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.1
  http: ^1.0.0
  health: ^7.0.1
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.0
  permission_handler: ^10.3.0
  get_it: ^7.6.0
  dynamic_color: ^1.6.5
  flutter_phoenix: ^1.1.1
  uuid: ^3.0.7
  flutter_localizations:
    sdk: flutter
  local_auth: ^2.1.6
  package_info_plus: ^4.0.2
  relative_time: ^4.0.1
  # dynamic_icon_flutter: ^0.0.7
  dynamic_icon_flutter:
    git:
      url: https://github.com/ender-null/dynamic_icon_flutter.git
      ref: main
  home_widget: ^0.3.0
  collection: ^1.17.1
  syncfusion_flutter_charts: ^22.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  msix: ^3.15.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/AppIcons/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: fonts/Roboto/RobotoMono-Regular.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-Regular.ttf
        - asset: fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf

msix_config:
  display_name: LoveLust
  publisher_display_name: end.works
  store: false
  publisher: CN=E2B04482-A46E-40D9-BF38-4AFE3DD27617
  # publisher: CN=LoveLust, O=end.works, L=the end, S=end ville, C=EU
  identity_name: 15896end.works.LoveLust
  msix_version: 1.0.0.0

  certificate_path: winstore.pfx
  certificate_password: make me feel again

  sign_msix: false
  install_certificate: false
  # signtool_options: /fd SHA256 /f winstore.pfx /p 'make me feel again'

  logo_path: windows/runner/resources/app_icon.ico
  trim_logo: false
  capabilities: "internetClient"
  protocol_activation: https
  # languages: en-us
  app_uri_handler_hosts: lovelust.end.works
  execution_alias: lovelust
  add_execution_alias: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/splash.png
  #branding: assets/branding.png
  #branding_dark: assets/branding_dark.png
