name: lovelust
description: Track and take care of your sexual health
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.1
  http: ^1.0.0
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  permission_handler: ^11.3.1
  get_it: ^8.0.2
  dynamic_color: ^1.6.5
  flutter_phoenix: ^1.1.1
  uuid: ^4.5.1
  flutter_localizations:
    sdk: flutter
  local_auth: ^2.1.6
  package_info_plus: ^8.1.1
  relative_time: ^5.0.0
  flutter_dynamic_icon_plus: ^1.2.1
  home_widget: ^0.7.0
  collection: ^1.17.1
  google_fonts: ^6.2.1
  flutter_health_connect:
    git:
      url: https://github.com/rickcasson/flutter_health_connect.git
      ref: alpha6-updates
  health_kit_reporter: ^2.1.1
  table_calendar: ^3.1.2
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  msix: ^2.7.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/AppIcons/
    - fonts/Inter/static/
    - fonts/Nunito/static/

msix_config:
  display_name: LoveLust
  publisher_display_name: end.works
  store: false
  publisher: CN=E2B04482-A46E-40D9-BF38-4AFE3DD27617
  # publisher: CN=LoveLust, O=end.works, L=the end, S=end ville, C=EU
  identity_name: 15896end.works.LoveLust
  msix_version: 1.0.0.0

  certificate_path: winstore.pfx
  certificate_password: make me feel again

  sign_msix: false
  install_certificate: false
  # signtool_options: /fd SHA256 /f winstore.pfx /p 'make me feel again'

  logo_path: windows/runner/resources/app_icon.ico
  trim_logo: false
  capabilities: "internetClient"
  protocol_activation: https
  # languages: en-us
  app_uri_handler_hosts: lovelust.end.works
  execution_alias: lovelust
  add_execution_alias: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/splash.png
  #branding: assets/branding.png
  #branding_dark: assets/branding_dark.png
