name: Android

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: "gradle"

      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Test
        run: flutter test

      - name: Install 1Password CLI
        run: |
          wget "https://cache.agilebits.com/dist/1P/op2/pkg/v2.18.0/op_linux_amd64_v2.18.0.zip" -O op.zip
          unzip -d op op.zip
          sudo mv op/op /usr/local/bin
          rm -r op.zip op

          op user get --me
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Get keystore
        run: |
          op read -o ./android/key.properties "op://end.works/Play Store keystore/key.properties"
          op read -o ./android/app/upload-keystore.jks "op://end.works/Play Store keystore/upload-keystore.jks"
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Build app bundle
        run: flutter build appbundle

      - name: Build apk
        run: flutter build apk

      - name: Upload app bundle
        uses: actions/upload-artifact@v3
        with:
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload mapping file
        uses: actions/upload-artifact@v3
        with:
          path: build/app/outputs/mapping/release/mapping.txt

      - name: Upload debug symbols
        uses: actions/upload-artifact@v3
        with:
          name: debugSymbols
          path: build/app/intermediates/merged_native_libs/release/out/lib

  deploy:
    name: Deploy to Play Store
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1.2.0
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SERVICE_ACCOUNT_JSON: op://end.works/Google Play Console Service account/credential

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - run: tree

      - name: Release build to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ env.SERVICE_ACCOUNT_JSON }}
          packageName: works.end.LoveLust
          releaseFiles: app-release.aab/app-release.aab
          mappingFile: mapping.txt/mapping.txt
          debugSymbols: debugSymbols
          track: alpha
          status: completed
