name: Android

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    outputs:
      apk: ${{ steps.output.outputs.apk }}
      app-bundle: ${{ steps.output.outputs.app-bundle }}
      mapping: ${{ steps.output.outputs.mapping }}
      debug-symbols: ${{ steps.output.outputs.debug-symbols }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: "gradle"

      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Test
        run: flutter test

      - name: Install 1Password CLI
        run: |
          wget "https://cache.agilebits.com/dist/1P/op2/pkg/v2.18.0/op_linux_amd64_v2.18.0.zip" -O op.zip
          unzip -d op op.zip
          sudo mv op/op /usr/local/bin
          rm -r op.zip op

          op user get --me
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Get keystore
        run: |
          op read -o ./android/key.properties "op://end.works/Play Store keystore/key.properties"
          op read -o ./android/app/upload-keystore.jks "op://end.works/Play Store keystore/upload-keystore.jks"
          export SERVICE_ACCOUNT_JSON=op://end.works/Google Play Console Service account/credential
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Build app bundle
        run: flutter build appbundle

      # - name: Build apk
      #   run: flutter build apk

      # - name: Upload apk
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: apk
      #     path: build/app/outputs/flutter-apk/app-release.apk

      # - name: Upload app bundle
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: app-bundle
      #     path: build/app/outputs/bundle/release/app-release.aab

      # - name: Upload mapping
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: mapping
      #     path: build/app/outputs/mapping/release/mapping.txt

      # - name: Upload debug symbols
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: debug-symbols
      #     path: build/app/intermediates/merged_native_libs/release/out/lib

      - run: tree

      - name: Release build to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ env.SERVICE_ACCOUNT_JSON }}
          packageName: works.end.LoveLust
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          mappingFile: build/app/outputs/mapping/release/mapping.txt
          debugSymbols: build/app/intermediates/merged_native_libs/release/out/lib
          track: alpha
          status: completed
