name: Build Android

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: semeru
          java-version: 17

      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Test
        run: flutter test

      - name: Install 1Password CLI
        run: |
          wget "https://cache.agilebits.com/dist/1P/op2/pkg/v2.18.0/op_linux_amd64_v2.18.0.zip" -O op.zip
          unzip -d op op.zip
          sudo mv op/op /usr/local/bin
          rm -r op.zip op

          op user get --me
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Get keystore
        run: |
          op read -o ./android/key.properties "op://end.works/Play Store keystore/key.properties"
          op read -o ./android/app/upload-keystore.jks "op://end.works/Play Store keystore/upload-keystore.jks"
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Build app bundle
        run: flutter build appbundle

      - name: Build apk
        run: flutter build apk

      - name: Upload app bundle
        uses: actions/upload-artifact@v3
        with:
          name: lovelust.aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: lovelust.apk
          path: build/app/outputs/flutter-apk/app-release.apk
