name: Flutter build

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Flutter build
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
          flutter test
          flutter build apk
          flutter build appbundle

      - name: Generate apk
        uses: actions/upload-artifact@v2
        with:
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Generate appbundle
        uses: actions/upload-artifact@v2
        with:
          path: build/app/outputs/bundle/release/app-release.aab

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Flutter build
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - run: flutter pub get
          flutter test
          flutter build ios --release --no-codesign
          flutter build ipa

      - name: Generate release build
        uses: actions/upload-artifact@v2
        with:
          path: build/ios/iphoneos/Runner.app
