name: Flutter iOS

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Flutter build
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Test
        run: flutter test

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Upload iOS app
        uses: actions/upload-artifact@v3
        with:
          name: lovelust.app
          path: build/ios/iphoneos/Runner.app
