name: iOS (self-hosted)

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: [self-hosted, macOS]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get secrets
        run: |
          export APPSTORE_API_KEY_ID=$(op read "op://end.works/App Store Connect API/app store api key id")
          export APPSTORE_API_PRIVATE_KEY_BASE64=$(op read "op://end.works/App Store Connect API/app store api private key")
          export APPSTORE_ISSUER_ID=$(op read "op://end.works/App Store Connect API/app store issuer id")
          export BUILD_CERTIFICATE_BASE64=$(op read "op://end.works/App Store Connect API/build certificate")
          export BUILD_CERTIFICATE_PRIVATE_KEY_BASE64=$(op read "op://end.works/App Store Connect API/build certificate private key")
          export P12_PASSWORD=$(op read "op://end.works/App Store Connect API/p12 password")
          export PROVISION_PROFILE_BASE64=$(op read "op://end.works/App Store Connect API/provision profile app store")
          export KEYCHAIN_PASSWORD=$(op read "op://end.works/App Store Connect API/keychain password")
          export CODE_SIGNING_IDENTITY=$(op read "op://end.works/App Store Connect API/code signing identity")
          export TEAM_ID=$(op read "op://end.works/App Store Connect API/team id")
          echo "APPSTORE_API_KEY_ID=$APPSTORE_API_KEY_ID" >> $GITHUB_ENV
          echo "APPSTORE_API_PRIVATE_KEY_BASE64=$APPSTORE_API_PRIVATE_KEY_BASE64" >> $GITHUB_ENV
          echo "APPSTORE_ISSUER_ID=$APPSTORE_ISSUER_ID" >> $GITHUB_ENV
          echo "BUILD_CERTIFICATE_BASE64=$BUILD_CERTIFICATE_BASE64" >> $GITHUB_ENV
          echo "BUILD_CERTIFICATE_PRIVATE_KEY_BASE64=$BUILD_CERTIFICATE_PRIVATE_KEY_BASE64" >> $GITHUB_ENV
          echo "P12_PASSWORD=$P12_PASSWORD" >> $GITHUB_ENV
          echo "PROVISION_PROFILE_BASE64=$PROVISION_PROFILE_BASE64" >> $GITHUB_ENV
          echo "KEYCHAIN_PASSWORD=$KEYCHAIN_PASSWORD" >> $GITHUB_ENV
          echo "CODE_SIGNING_IDENTITY=$CODE_SIGNING_IDENTITY" >> $GITHUB_ENV
          echo "TEAM_ID=$TEAM_ID" >> $GITHUB_ENV
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Get release name
        run: |
          echo "COMMIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT_NUMBER=$(git rev-list --count main)" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Build the Flutter iOS project
        run: flutter build ipa --build-number=${{ env.COMMIT_NUMBER }}

      - name: Publish the app to App Store Connect
        run: xcrun altool --upload-app --type ios -f build/ios/ipa/*.ipa --apiKey ${{ env.APPSTORE_API_KEY_ID }} --apiIssuer ${{ env.APPSTORE_ISSUER_ID }}
