name: iOS

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build
    # runs-on: macos-latest
    runs-on: [self-hosted, macOS]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
          cache: true

      - name: Disable telemetry
        run: flutter --disable-telemetry

      - name: Cache 1password-cli
        id: cache-op
        uses: actions/cache@v3
        env:
          cache-name: cache-op
        with:
          path: /usr/local/bin/op
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - if: ${{ steps.cache-op.outputs.cache-hit != 'true' }}
        name: Install 1Password CLI
        run: |
          if ! command -v op &> /dev/null
          then
            brew install --cask 1password/tap/1password-cli
            exit
          fi

      - name: Get secrets
        run: |
          export APPSTORE_API_KEY_ID=$(op read "op://end.works/App Store Connect API/app store api key id")
          export APPSTORE_API_PRIVATE_KEY_BASE64=$(op read "op://end.works/App Store Connect API/app store api private key")
          export APPSTORE_ISSUER_ID=$(op read "op://end.works/App Store Connect API/app store issuer id")
          export BUILD_CERTIFICATE_BASE64=$(op read "op://end.works/App Store Connect API/build certificate")
          export BUILD_CERTIFICATE_PRIVATE_KEY_BASE64=$(op read "op://end.works/App Store Connect API/build certificate private key")
          export P12_PASSWORD=$(op read "op://end.works/App Store Connect API/p12 password")
          export PROVISION_PROFILE_BASE64=$(op read "op://end.works/App Store Connect API/provision profile app store")
          export KEYCHAIN_PASSWORD=$(op read "op://end.works/App Store Connect API/keychain password")
          export CODE_SIGNING_IDENTITY=$(op read "op://end.works/App Store Connect API/code signing identity")
          export TEAM_ID=$(op read "op://end.works/App Store Connect API/team id")
          echo "APPSTORE_API_KEY_ID=$APPSTORE_API_KEY_ID" >> $GITHUB_ENV
          echo "APPSTORE_API_PRIVATE_KEY_BASE64=$APPSTORE_API_PRIVATE_KEY_BASE64" >> $GITHUB_ENV
          echo "APPSTORE_ISSUER_ID=$APPSTORE_ISSUER_ID" >> $GITHUB_ENV
          echo "BUILD_CERTIFICATE_BASE64=$BUILD_CERTIFICATE_BASE64" >> $GITHUB_ENV
          echo "BUILD_CERTIFICATE_PRIVATE_KEY_BASE64=$BUILD_CERTIFICATE_PRIVATE_KEY_BASE64" >> $GITHUB_ENV
          echo "P12_PASSWORD=$P12_PASSWORD" >> $GITHUB_ENV
          echo "PROVISION_PROFILE_BASE64=$PROVISION_PROFILE_BASE64" >> $GITHUB_ENV
          echo "KEYCHAIN_PASSWORD=$KEYCHAIN_PASSWORD" >> $GITHUB_ENV
          echo "CODE_SIGNING_IDENTITY=$CODE_SIGNING_IDENTITY" >> $GITHUB_ENV
          echo "TEAM_ID=$TEAM_ID" >> $GITHUB_ENV
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Get release name
        run: |
          FULL_VERSION=$(echo | grep -i -e "version: " pubspec.yaml)
          BUILD_VERSION=$(echo $FULL_VERSION | cut -d " " -f 2 | cut -d "+" -f 1)
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
          echo "COMMIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT_NUMBER=$(git rev-list --count main)" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Generate release notes
        run: echo "APP_STORE_CONNECT_WHATS_NEW=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Install the Codemagic CLI tools
        run: pip3 install codemagic-cli-tools

      - name: Set the environment variables
        run: |
          echo "APP_STORE_CONNECT_ISSUER_ID=${{ env.APPSTORE_ISSUER_ID }}" >> $GITHUB_ENV
          echo "APP_STORE_CONNECT_KEY_IDENTIFIER=${{ env.APPSTORE_API_KEY_ID }}" >> $GITHUB_ENV
          echo "CERTIFICATE_PRIVATE_KEY_PASSWORD=${{ env.P12_PASSWORD }}" >> $GITHUB_ENV

      - name: Import App Store Connect API private key
        run: |
          PRIVATE_KEYS_DIR=~/.private_keys
          mkdir -p $PRIVATE_KEYS_DIR
          PRIVATE_KEY_PATH=$PRIVATE_KEYS_DIR/AuthKey_"${{ env.APPSTORE_API_KEY_ID }}".p8
          echo -n "${{ env.APPSTORE_API_PRIVATE_KEY_BASE64 }}" | base64 --decode -o $PRIVATE_KEY_PATH
          echo "APP_STORE_CONNECT_PRIVATE_KEY=@file:$PRIVATE_KEY_PATH" >> $GITHUB_ENV

      - name: Get private key used to generate the certificate
        run: |
          CERTIFICATES_DIR=~/Library/MobileDevice/Certificates
          mkdir -p $CERTIFICATES_DIR
          CERTIFICATE_KEY_PATH=$CERTIFICATES_DIR/cert.key
          echo -n "${{ env.BUILD_CERTIFICATE_PRIVATE_KEY_BASE64 }}" | base64 --decode -o $CERTIFICATE_KEY_PATH
          echo "CERTIFICATE_PRIVATE_KEY=@file:$CERTIFICATE_KEY_PATH" >> $GITHUB_ENV

      - name: Set up a new temporary keychain
        run: keychain initialize

      - name: Set system default keychain
        run: keychain use-login

      - name: Fetch the code signing files from App Store Connect
        run: app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) --type IOS_APP_STORE --create

      - name: Add the fetched certificates to keychain
        run: keychain add-certificates --certificate-password='${{ env.P12_PASSWORD }}'

      - name: Update the Xcode project settings to use fetched code signing profiles
        run: xcode-project use-profiles --export-options-plist=ios/exportOptions.plist

      - uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 5G

      - name: Install Flutter dependencies
        run: flutter packages pub get

      - name: Install dependencies
        run: flutter pub get

      - name: Install Pods
        run: find . -name "Podfile" -execdir pod install \;

      - name: Build the Flutter iOS project
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          export CCACHE_SLOPPINESS=clang_index_store,file_stat_matches,include_file_ctime,include_file_mtime,ivfsoverlay,pch_defines,modules,system_headers,time_macros
          export CCACHE_FILECLONE=true
          export CCACHE_DEPEND=true
          export CCACHE_INODECACHE=true
          ccache -s
          flutter build ipa --build-number=${{ env.COMMIT_NUMBER }} --export-options-plist=ios/exportOptions.plist --verbose

      - name: Publish the app to App Store Connect
        run: app-store-connect publish --path $(find $(pwd) -name "*.ipa")

      - name: Set system default keychain
        run: keychain use-login
