name: Windows

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Enable windows build
        run: flutter config --enable-windows-desktop

      - name: Test
        run: flutter test

      - name: Install 1Password CLI
        run: |
          $arch = (Get-CimInstance Win32_OperatingSystem).OSArchitecture
          switch ($arch) {
              '64-bit' { $opArch = 'amd64'; break }
              '32-bit' { $opArch = '386'; break }
              Default { Write-Error "Sorry, your operating system architecture '$arch' is unsupported" -ErrorAction Stop }
          }
          $installDir = Join-Path -Path $pwd -ChildPath 'op'
          Invoke-WebRequest -Uri "https://cache.agilebits.com/dist/1P/op2/pkg/v2.18.0/op_windows_$($opArch)_v2.18.0.zip" -OutFile op.zip
          Expand-Archive -Path op.zip -DestinationPath $installDir -Force
          Remove-Item -Path op.zip
          Copy-Item "$installDir/op.exe" -Destination "./"

      - name: Get secrets
        run: |
          $env:AZURE_AD_TENANT_ID = $(./op.exe read "op://end.works/Windows Store/azure ad tennant id")
          $env:AZURE_AD_CLIENT_ID = $(./op.exe read "op://end.works/Windows Store/azure ad client id")
          $env:AZURE_AD_CLIENT_SECRET = $(./op.exe read "op://end.works/Windows Store/azure ad client secret")
          $env:SELLER_ID = $(./op.exe read "op://end.works/Windows Store/seller id")
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Get release name
        run: |
          $env:BUILD_BRANCH = $(git rev-parse --abbrev-ref HEAD)
          $env:BUILD_HASH = $(git rev-parse --short HEAD)
          $env:BUILD_NUMBER = $(git rev-list --count main)

      - name: Variables
        run: |
          $BUILD_BRANCH = [Environment]::GetEnvironmentVariable('BUILD_BRANCH', [System.EnvironmentVariableTarget]::Machine)
          $BUILD_HASH = [Environment]::GetEnvironmentVariable('BUILD_HASH', [System.EnvironmentVariableTarget]::Machine)
          $BUILD_NUMBER = [Environment]::GetEnvironmentVariable('BUILD_NUMBER', [System.EnvironmentVariableTarget]::Machine)
          $AZURE_AD_TENANT_ID = [Environment]::GetEnvironmentVariable('AZURE_AD_TENANT_ID', [System.EnvironmentVariableTarget]::Machine)
          $AZURE_AD_CLIENT_ID = [Environment]::GetEnvironmentVariable('AZURE_AD_CLIENT_ID', [System.EnvironmentVariableTarget]::Machine)
          $AZURE_AD_CLIENT_SECRET = [Environment]::GetEnvironmentVariable('AZURE_AD_CLIENT_SECRET', [System.EnvironmentVariableTarget]::Machine)
          $SELLER_ID = [Environment]::GetEnvironmentVariable('SELLER_ID', [System.EnvironmentVariableTarget]::Machine)
          echo "$BUILD_BRANCH"
          echo "$BUILD_HASH"
          echo "$BUILD_NUMBER"
          echo "$AZURE_AD_TENANT_ID"
          echo "$AZURE_AD_CLIENT_ID"
          echo "$AZURE_AD_CLIENT_SECRET"
          echo "$SELLER_ID"

      - name: Build windows app
        run: flutter build windows --release --build-number=$BUILD_NUMBER

      - uses: microsoft/setup-msstore-cli@v1

      - name: Configure the Microsoft Store CLI
        run: msstore reconfigure --tenantId $AZURE_AD_TENANT_ID --clientId $AZURE_AD_CLIENT_ID --clientSecret $AZURE_AD_CLIENT_SECRET --sellerId $SELLER_ID

      - name: Create MSIX
        run: msstore package .

      - name: Publish MSIX to the Microsoft Store
        run: msstore publish -v
