name: Windows

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Enable windows build
        run: flutter config --enable-windows-desktop

      - name: Test
        run: flutter test

      - name: Install 1Password CLI
        run: |
          $arch = (Get-CimInstance Win32_OperatingSystem).OSArchitecture
          switch ($arch) {
              '64-bit' { $opArch = 'amd64'; break }
              '32-bit' { $opArch = '386'; break }
              Default { Write-Error "Sorry, your operating system architecture '$arch' is unsupported" -ErrorAction Stop }
          }
          $installDir = Join-Path -Path $pwd -ChildPath 'op'
          Invoke-WebRequest -Uri "https://cache.agilebits.com/dist/1P/op2/pkg/v2.18.0/op_windows_$($opArch)_v2.18.0.zip" -OutFile op.zip
          Expand-Archive -Path op.zip -DestinationPath $installDir -Force
          Remove-Item -Path op.zip
          Copy-Item "$installDir/op.exe" -Destination "./"

      - name: Get secrets
        run: |
          "PARTNER_CENTER_TENANT_ID=$(./op.exe read "op://end.works/Microsoft Store Dev CLI/tennant id")" >> $env:GITHUB_ENV
          "PARTNER_CENTER_SELLER_ID=$(./op.exe read "op://end.works/Microsoft Store Dev CLI/seller id")" >> $env:GITHUB_ENV
          "PARTNER_CENTER_CLIENT_ID=$(./op.exe read "op://end.works/Microsoft Store Dev CLI/client id")" >> $env:GITHUB_ENV
          "PARTNER_CENTER_CLIENT_SECRET=$(./op.exe read "op://end.works/Microsoft Store Dev CLI/client secret")" >> $env:GITHUB_ENV
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Get release name
        run: |
          "BUILD_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $env:GITHUB_ENV
          "BUILD_HASH=$(git rev-parse --short HEAD)" >> $env:GITHUB_ENV
          "BUILD_NUMBER=$(git rev-list --count main)" >> $env:GITHUB_ENV

      - name: Refresh environment
        run: |
          Import-Module "$env:ChocolateyInstall/helpers/chocolateyInstaller.psm1"
          refreshenv

      - name: Build windows app
        run: flutter build windows --release --build-number=$env:BUILD_NUMBER

      - uses: microsoft/setup-msstore-cli@v1

      - name: Configure the Microsoft Store CLI
        run: msstore reconfigure --tenantId $env:PARTNER_CENTER_TENANT_ID --sellerId $env:PARTNER_CENTER_SELLER_ID --clientId $env:PARTNER_CENTER_CLIENT_ID --clientSecret $env:PARTNER_CENTER_CLIENT_SECRET

      - name: Create MSIX
        run: msstore package --version 1.0.0.$env:BUILD_NUMBER

      - name: Publish MSIX to the Microsoft Store
        run: msstore publish build/windows/runner/Release -v
